dist: trusty
sudo: required
language: node_js
node_js:
  - "8.11.3"
cache:
  yarn: true
  directories:
    - "node_modules"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > .npmrc
install:
  - yarn
script:
  - yarn run test
  - codecov
before_deploy:
  - yarn run compile
deploy:
  provider: script
  script:
    - yarn run publish-cutoff
  skip_cleanup: true
  on:
    tags: true
    branch: master