name: Repodog build and publish

on:
  workflow_call:
    inputs:
      node-version:
        default: '20.10.0'
        required: false
        type: string
      package-manager:
        default: 'pnpm'
        required: false
        type: string
      package-manager-version:
        required: false
        type: string
      yarn-version:
        default: 1
        required: false
        type: number
    secrets:
      npm_auth_token:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Log build trigger
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_type }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install yarn classic
        if: inputs.package-manager == 'yarn' && inputs.yarn-version == 1
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash
          export PATH=$HOME/.yarn/bin:$PATH

      - name: Install modern yarn
        if: inputs.package-manager == 'yarn' && inputs.yarn-version != 1
        run: |
          corepack enable
          corepack prepare yarn@${{ inputs.package-manager-version }} --activate

      - name: Install pnpm
        if: inputs.package-manager == 'pnpm'
        run: |
          corepack enable
          corepack prepare pnpm@${{ inputs.package-manager-version }} --activate

      - name: Install dependencies with pnpm
        if: inputs.package-manager == 'pnpm'
        run: pnpm install

      - name: Install dependencies with yarn
        if: inputs.package-manager == 'yarn'
        run: yarn install

      - name: Install dependencies with npm
        if: inputs.package-manager == 'npm'
        run: npm install

      - name: Lint dependencies
        run: npm run --if-present syncpack

      - name: Build packages
        run: NODE_ENV=production npm run --if-present build

      - name: Lint packages
        run: npm run --if-present lint

      - name: Type check packages
        run: npm run --if-present type-check

      - name: Run unit tests
        run: npm run --if-present test

      - name: Publish packages
        if: github.ref_type == 'tag'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.npm_auth_token }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> .npmrc
          npm run --if-present repodog -- publish --verbose