name: Repodog build and publish

on:
  workflow_call:
    inputs:
      package-manager:
        default: 'pnpm'
        required: false
        type: string
    secrets:
      npm_auth_token:
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Log build trigger
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_type }}

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise install

      - name: Install dependencies with pnpm
        if: inputs.package-manager == 'pnpm'
        run: pnpm install

      - name: Install dependencies with yarn
        if: inputs.package-manager == 'yarn'
        run: yarn install

      - name: Install dependencies with npm
        if: inputs.package-manager == 'npm'
        run: npm install

      - name: Lint dependencies
        run: npm run --if-present syncpack

      - name: Build packages
        run: NODE_ENV=production npm run --if-present build

      - name: Lint packages
        run: npm run --if-present lint

      - name: Type check packages
        run: npm run --if-present type-check

      - name: Run unit tests
        run: npm run --if-present test

      - name: Publish packages
        if: github.ref_type == 'tag'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.npm_auth_token }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> .npmrc
          npm run --if-present repodog -- publish --verbose
